implemented means of tracking internet availability in the period of a day

diff --git a/gpc b/gpc
--- a/gpc
+++ b/gpc
@@ -73,6 +73,7 @@ if [ -f "$SETTINGS" ]
 		echo -e "MEMORY=true" >> $SETTINGS
 		echo -e "CPU=true" >> $SETTINGS
 		echo -e "SELINUX=true" >> $SETTINGS
+		echo -e "UPDATES=true" >> $SETTINGS
 		echo -e "#Adjust settings for color coding; below moderate is green, below critical is yellow and above is red" >> $SETTINGS
 		echo -e "#Memory Settings:" >> $SETTINGS
 		echo -e "MODERATE_MEM=60" >> $SETTINGS
@@ -91,32 +92,42 @@ fi
 
 
 #Print the status of a service:
-NM_STATUS=$(service NetworkManager status | awk 'NR == 3 {print $2}')
-if [ $NM_STATUS = "active" ]
-	then
-	echo -e "[ \e[0;32mNetworking\e[0m ]" >> $MOTD
-	else
-	echo -e "[ \e[0;31mNetworking\e[0m ]" >> $MOTD
+#NM_STATUS=$(service NetworkManager status | awk 'NR == 3 {print $2}')
+#if [ $NM_STATUS = "active" ]
+#	then
+#	echo -e "[ \e[0;32mNetworking\e[0m ]" >> $MOTD
+#	else
+#	echo -e "[ \e[0;31mNetworking\e[0m ]" >> $MOTD
+#fi
+
+#Detect and monitor Internet availability:
+CUR_HOUR=$(date +"%H")
+if [ $CUR_HOUR = "00" ]
+	then rm .gplog; touch .gplog
 fi
 
-#Detect Internet availability:
 GOOGLE_STATUS=$(ping -c4 google.com | awk 'NR == 8 {print $6}' | cut -c1)
 if [ $GOOGLE_STATUS -eq 0 ]
 	then
 	INT_STATUS="true"
 	INT_COL="\e[0;32mINT\e[0m"
-	elif [ $GOOGLE_STATUS -gt 0  ]
+	echo -ne "\e[0;32m$CUR_HOUR\e[0m" >> .gplog
+	elif [ $GOOGLE_STATUS -gt 0 ]
 		then
 		INT_STATUS="false"
 		INT_COL="\e[1;33mINT\e[0m"
+		echo -ne "\e[1;33m$CUR_HOUR\e[0m" >> .gplog
 	else
 	INT_STATUS="false"
 	INT_COL="\e[0;31mINT\e[0m"
+	echo -ne "\e[0;32m$CUR_HOUR\e[0m" >> .gplog
 fi
+
+#echo -e "\e[37;45m$CUR_HOUR\e[0m"
 
 if [ $INTERNET = "true" ]
 	then
-	echo -e "[ $INT_COL ]" >> $MOTD
+	echo -e "[ $INT_COL ][ $(cat .gplog) ]" >> $MOTD
 fi
 
 
@@ -162,18 +173,21 @@ if [ $INT_STATUS = "false" ]
 	then
 	echo -e "[ \e[0;31m$PACKAGE_MANAGER\e[0m ][ No connection to internet ]" >> $MOTD
 	else
-		yum check-update > .gplog
-		if [ -z "$?" -o "$?" != "0" -a "$?" != "100" ]
+		if [ $UPDATES = "true" ]
 		then
-		echo -e "[ \e[0;31m$PACKAGE_MANAGER\e[0m ][ $PACKAGE_MANAGER exited with error code $? ]" >> $MOTD
-		else
-		NUM_UPDATES=$(grep -c "updates" .gplog)
-		fi
-			if [ "$NUM_UPDATES" != "0" ]
+			yum check-update > .pmlog
+			if [ -z "$?" -o "$?" != "0" -a "$?" != "100" ]
+			then
+			echo -e "[ \e[0;31m$PACKAGE_MANAGER\e[0m ][ $PACKAGE_MANAGER exited with error code $? ]" >> $MOTD
+			else
+			NUM_UPDATES=$(grep -c "updates" .pmlog)
+			fi
+				if [ "$NUM_UPDATES" != "0" ]
 				then
 				echo -e "[ \e[1;33m$PACKAGE_MANAGER\e[0m ][ $NUM_UPDATES update(s) available ]" >> $MOTD
 				else
 				echo -e "[ \e[0;32m$PACKAGE_MANAGER\e[0m ][ $NUM_UPDATES updates available, System is up to date ]" >> $MOTD
+			fi
 			fi
 fi
 
