fixed bug in yum update code, however another odd bug seems to persist. occasionally, yum check-update with exit with error code 0, but print an error and sometimes it will exit with error =/= 0 and print no errors.

diff --git a/gpc b/gpc
--- a/gpc
+++ b/gpc
@@ -139,9 +139,10 @@ if [ $INT_STATUS = "false" ]
 	echo -e "[ \e[0;31m$PACKAGE_MANAGER\e[0m ][ No connection to internet ]" >> $MOTD
 	else
 		yum check-update > .gplog
+		echo $?
 		if [ $? -ne 0 ]
 		then
-		echo -e "[ \e0;31m$PACKAGE_MANAGER\e[0m ][ $PACKAGE_MANAGER exited with error code $? ]" >> $MOTD
+		echo -e "[ \e[0;31m$PACKAGE_MANAGER\e[0m ][ $PACKAGE_MANAGER exited with error code $? ]" >> $MOTD
 		else
 		NUM_UPDATES=$(grep -c "updates" .gplog)
 		fi
