Removed Updates monitoring Removed Selinux alerts monitory Moved Selinux status to system info Re-implemented monitoring as functions

diff --git a/gpc b/gpc
--- a/gpc
+++ b/gpc
@@ -76,8 +76,6 @@ if [ -f "$SETTINGS" ]
 		echo -e "INTERNET=true" >> $SETTINGS
 		echo -e "MEMORY=true" >> $SETTINGS
 		echo -e "CPU=true" >> $SETTINGS
-		echo -e "SELINUX=true" >> $SETTINGS
-		echo -e "UPDATES=true" >> $SETTINGS
 		echo -e "#Adjust settings for color coding; below moderate is green, below critical is yellow and above is red" >> $SETTINGS
 		echo -e "#Memory Settings:" >> $SETTINGS
 		echo -e "MODERATE_MEM=60" >> $SETTINGS
@@ -103,6 +101,8 @@ fi
 #	echo -e "[ \e[0;31mNetworking\e[0m ]" >> $MOTD
 #fi
 
+
+
 #Calculate the amount of time that has elapsed since the last execution of the script
 if [ -e "$MOTD" ]
 	then
@@ -111,8 +111,20 @@ if [ -e "$MOTD" ]
 	LAST_EXEC=31
 fi
 
-#Display overall system information
-echo -e "[ \e[0;32mSYS\e[0m ][ $(date) \e[0;32m-\e[0m Uptime: $(uptime | awk '{print $3}') \e[0;32m-\e[0m $HOSTNAME ]" >> $MOTD
+#Determine status of SELinux and display overall system information.
+#enforcing 	= green
+#permissive 	= yellow
+#disabled 	= red
+SEL_STATUS=$(sestatus | awk 'NR == 5 {print $3}')
+	if [ $SEL_STATUS = "enforcing" ]
+		then
+		echo -e "[ \e[0;32mSYS\e[0m ][ $(date) \e[0;32m-\e[0m Uptime: $(uptime | awk '{print $3}') \e[0;32m-\e[0m $HOSTNAME \e[0;32m-\e[0m \e[0;32mSEL\e[0m ]" >> $MOTD
+	elif [ $SEL_STATUS = "permissive" ]
+		then
+		echo -e "[ \e[0;32mSYS\e[0m ][ $(date) \e[0;32m-\e[0m Uptime: $(uptime | awk '{print $3}') \e[0;32m-\e[0m $HOSTNAME \e[0;32m-\e[0m \e[1;33mSEL\e[0m ]" >> $MOTD
+	else
+		echo -e "[ \e[0;32mSYS\e[0m ][ $(date) \e[0;32m-\e[0m Uptime: $(uptime | awk '{print $3}') \e[0;32m-\e[0m $HOSTNAME \e[0;32m-\e[0 m\e[0;31mSEL\e[0m ]" >> $MOTD
+fi
 
 #Detect and monitor Internet availability:
 CUR_HOUR=$(date +"%H")
@@ -125,10 +137,13 @@ if [ -f ".gplog" -o $CUR_HOUR = "00"  ]
 	echo -ne "\n" >> .gplog
 fi
 
+
 #Template for appending text to the end of a line by it's number
 #awk -v OFS=" " 'NR == 1 { $(NF+1)="NO" };1' newfile > newerfile && cat newerfile > newfile && rm newerfile
 
-GOOGLE_STATUS=$(ping -c4 google.com | awk 'NR == 8 {print $6}' | cut -c1)
+#Check Internet Status by pinging 8.8.8.8, Google's Public DNS server that's only failed twice ever.
+function CHECK_WAN {
+GOOGLE_STATUS=$(ping -c4 8.8.8.8 | awk 'NR == 8 {print $6}' | cut -c1)
 if [ $GOOGLE_STATUS -eq 0 ]
 	then
 	INT_STATUS="true"
@@ -155,14 +170,12 @@ elif [ $GOOGLE_STATUS -gt 0 ]
 fi
 
 sed -i "s/\$CUR_HOUR/$CUR_HOUR/g" .gplog
+echo -e "[ $INT_COL ][ $(awk 'NR==1 {print}' .gplog)]" >> $MOTD
+}
 
-if [ $INTERNET = "true" ]
-	then
-	echo -e "[ $INT_COL ][ $(awk 'NR==1 {print}' .gplog)]" >> $MOTD
-fi
-
-#Calculates the system memory usage as a rounded integer percentage and prints to a log
-CUR_MEM=$(free | awk 'NR == 3 {print $3} NR == 2 {print $2}' | paste -sd" " | awk 'NR ==1 {print $2/$1*100}' | awk '{printf("%d\n",$1 + 0.5)}')
+#Calculates the system memory usage as a rounded integer percentage and prints to a log.
+function CHECK_MEM {
+CUR_MEM=$(free | awk 'NR == 2 {print $3} NR == 2 {print $2}' | paste -sd" " | awk 'NR == 1 {print $1/$2*100}' | awk '{printf("%d\n",$1 + 0.5)}')
 if [ $CUR_MEM -lt 60 ]
 	then
 	CUR_MEM_COL="\e[0;32m"
@@ -172,79 +185,56 @@ if [ $CUR_MEM -lt 60 ]
 	else
 	CUR_MEM_COL="\e0;31m"
 fi
-
-if [ $MEMORY = "true" ]
-	then
 	echo -e "[ $CUR_MEM_COL \bRAM\e[0m ][ $CUR_MEM_COL \b%$CUR_MEM\e[0m memory in use ]" >> $MOTD
-fi
+}
 
-
+#Check CPU usage, scale to multi-threaded systems
+function CHECK_CPU {
 CUR_CPU=$(top -bn1 | grep "Cpu(s)" | sed "s/.*, *\([0-9.]*\)%* id.*/\1/" | awk '{print $1}' | awk '{printf("%d\n",$1 + 0.5)}')
 #Possibly the least elegant way to calculate average cpu usage and normalize to cpu core count:
 AVE_CPU=$(echo -e "$(echo -e "($(uptime | cut -d" " -f14) / $(cat /proc/cpuinfo | grep -c "processor")) * 100" | bc -l) / 1 " | bc)
-if [ $CUR_CPU -lt $MODERATE_CPU ] && [ $AVE_CPU -lt $MODERATE_CPU ]
+if [ $AVE_CPU -lt $MODERATE_CPU ]
         then
 	CPU_COL="\e[0;32m"
-        elif [ $CUR_CPU -ge $MODERATE_CPU -a $CUR_CPU -lt $CRITICAL_CPU ] && [ $AVE_CPU -ge $MODERATE_CPU -o $AVE_CPU -lt $CRITICAL_CPU ]
+        elif [ $AVE_CPU -ge $MODERATE_CPU -a $AVE_CPU -lt $CRITICAL_CPU ] -o $AVE_CPU -lt $CRITICAL_CPU ]
         then
 	CPU_COL="\e[1;33m"
         else
 	CPU_COL="\e[0;31m"
 fi
-
-if [ $CPU = "true" ]
-	then
-	echo -e "[ $CPU_COL \bCPU\e[0m ][ $CPU_COL \b%$CUR_CPU\e[0m CPU in use, $CPU_COL%$AVE_CPU\e[0m ave 15m ]" >> $MOTD
-fi
+	echo -e "[ $CPU_COL \bCPU\e[0m ][ $CPU_COL%$AVE_CPU\e[0m ave 15m ]" >> $MOTD
+}
 
 
-#Determine how many (if any) updates are available.
-if [ $INT_STATUS = "false" ]
-	then
-	echo -e "[ \e[0;31m$PACKAGE_MANAGER\e[0m ][ No connection to internet ]" >> $MOTD
-	else
-		if [ $UPDATES = "true" ]
-		then
-			yum check-update > .pmlog
-			if [ -z "$?" -o "$?" != "0" -a "$?" != "100" ]
-			then
-			echo -e "[ \e[0;31m$PACKAGE_MANAGER\e[0m ][ $PACKAGE_MANAGER exited with error code $? ]" >> $MOTD
-			else
-			NUM_UPDATES=$(grep -c "updates" .pmlog)
-			fi
-				if [ "$NUM_UPDATES" != "0" ]
-				then
-				echo -e "[ \e[1;33m$PACKAGE_MANAGER\e[0m ][ $NUM_UPDATES update(s) available ]" >> $MOTD
-				else
-				echo -e "[ \e[0;32m$PACKAGE_MANAGER\e[0m ][ $NUM_UPDATES updates available, System is up to date ]" >> $MOTD
-			fi
-			fi
-fi
+#Determine how many (if any) updates are available. Disabled because yum check-update is behaving oddly.
 
-#Determine status of SELinux and display how many (if any) alerts there are:
-#enforcing 	= green
-#permissive 	= yellow
-#disabled 	= red
-SEL_STATUS=$(sestatus | awk 'NR == 5 {print $3}')
-SEL_ALERTS=$(sealert -l* | grep -c "denied") 
-if [ $SEL_ALERTS -eq 0 ]
-	then
-	SEL_ALERT_COL="\e[0;32m"
-	else
-	SEL_ALERT_COL="\e[0;31m"
-fi
+#function CHECK_YUM {
+#if [ $INT_STATUS = "false" ]
+#	then
+#	echo -e "[ \e[0;31m$PACKAGE_MANAGER\e[0m ][ No connection to internet ]" >> $MOTD
+#	else
+#			yum check-update > .pmlog
+#			if [ -z "$?" -o "$?" != "0" -a "$?" != "100" ]
+#			then
+#			echo -e "[ \e[0;31m$PACKAGE_MANAGER\e[0m ][ $PACKAGE_MANAGER exited with error code $? ]" >> $MOTD
+#			else
+#			NUM_UPDATES=$(grep -c "updates" .pmlog)
+#			fi
+#				if [ "$NUM_UPDATES" != "0" ]
+#					then
+#				echo -e "[ \e[1;33m$PACKAGE_MANAGER\e[0m ][ $NUM_UPDATES update(s) available ]" >> $MOTD
+#					else
+#				echo -e "[ \e[0;32m$PACKAGE_MANAGER\e[0m ][ $NUM_UPDATES updates available, System is up to date ]" >> $MOTD
+#				fi
+#fi
+#}
 
-if [ $SELINUX = "true" ]
-	then
-	if [ $SEL_STATUS = "enforcing" ]
-		then
-		echo -e "[ \e[0;32mSEL\e[0m ][ $SEL_ALERT_COL$SEL_ALERTS alert(s)\e[0m ]" >> $MOTD
-	elif [ $SEL_STATUS = "permissive" ]
-		then
-		echo -e "[ \e[1;33mSEL\e[0m ][ $SEL_ALERT_COL$SEL_ALERTS alert(s)\e[0m ]" >> $MOTD
-	else
-		echo -e "[ \e[0;31mSEL\e[0m ][ $SEL_ALERT_COL$SEL_ALERTS alert(s)\e[0m ]" >> $MOTD
-	fi
-fi
+
+#Execute and print output for all desired functions as by the user's configuration.
+if [ $INTERNET = "true" ]; then	CHECK_WAN; fi
+if [ $MEMORY = "true" ]; then CHECK_MEM; fi 
+if [ $CPU = "true" ]; then CHECK_CPU; fi
+#if [ $UPDATES = "true" ] && [ $INTERNET = "true" ]; then CHECK_YUM; fi
+
 cat $MOTD
 exit 0
